# Assignment Day 3 | 11th November 2020

# Question 1

In [2]:
# importing library
import numpy as np

In [3]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2

In [4]:
import numpy as np
# For list of integers 
lst1 = [] 
# For list of strings/chars 
lst2 = [] 

lst1 = [int(item) for item in input("Enter list1 : ").split()] 
lst2 = [item for item in input("Enter list2 : ").split()] 

arr1 = np.array(lst1)
arr2 = np.array(lst2)

concat = np.concatenate((arr1, arr2), axis= None)


print("lst1",lst1) 
print("lst2",lst2) 
print("arr1",arr1) 
print("arr2",arr2) 
print("concat",concat)
print("sort",np.sort(concat))

Enter list1 : 1 2 3 4 5
Enter list2 : Ten Nine Eight Seven Six
lst1 [1, 2, 3, 4, 5]
lst2 ['Ten', 'Nine', 'Eight', 'Seven', 'Six']
arr1 [1 2 3 4 5]
arr2 ['Ten' 'Nine' 'Eight' 'Seven' 'Six']
concat ['1' '2' '3' '4' '5' 'Ten' 'Nine' 'Eight' 'Seven' 'Six']
sort ['1' '2' '3' '4' '5' 'Eight' 'Nine' 'Seven' 'Six' 'Ten']


# Question 3

In [7]:
a = np.array([[1, 2, 3],[4, 5, 6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a.shape

(2, 3)

In [9]:
a.ndim

2

In [23]:
b = np.arange(45)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [20]:
b = np.arange(45).reshape(5,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [21]:
b.shape

(5, 3, 3)

In [22]:
b.ndim

3

# Question 4

In [49]:
x = np.array([1,2,3,4,5])
y = np.array([9,8,7,])

In [63]:
print(x.shape)
print()
print(y.ndim)

(5,)

1


In [64]:
rowx = x[:, np.newaxis]
print(rowx)
print()
print(rowx.shape)
print(row.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]]

(5, 1)
2


In [56]:
new_x = rowx + y
new_x

array([[10,  9,  8],
       [11, 10,  9],
       [12, 11, 10],
       [13, 12, 11],
       [14, 13, 12]])

In [57]:
rowy = y[:, np.newaxis]
rowy

array([[9],
       [8],
       [7]])

In [59]:
new_y = y + rowy
new_y

array([[18, 17, 16],
       [17, 16, 15],
       [16, 15, 14]])

# Question 5

In [87]:
m = np.array([1,2,3,4])
n = np.array([6,7,8,9])
vstack = np.vstack((m,n))
hstack = np.hstack((m,n))
print(vstack)
print()
print(hstack)

[[1 2 3 4]
 [6 7 8 9]]

[1 2 3 4 6 7 8 9]


In [90]:
m2 = np.array([[1],[2],[3],[4]])
n2 = np.array([[6],[7],[8],[9]])
vstack2 = np.vstack((m2,n2))
hstack2 = np.hstack((m2,n2))
print(vstack2)
print()
print(hstack2)

[[1]
 [2]
 [3]
 [4]
 [6]
 [7]
 [8]
 [9]]

[[1 6]
 [2 7]
 [3 8]
 [4 9]]


# Question 6

In [104]:
input_list = [1, 2, 2, 5, 8, 4, 4, 8, 5, 9, 9] 

# converting list to set 
# set removes duplicates
new_set = set(input_list) 
# length of the set gives total number of unique items.
print("No of unique items in the list are:", len(new_set))

No of unique items in the list are: 6


In [107]:
# creating an empty list 
lst = [] 
  
n = [int(item) for item in input("Enter the list items : ").split()] 
# converting list to set 
# set removes duplicates
new_set = set(n) 
# length of the set gives total number of unique items.
print("No of unique items in the list are:", len(new_set))

Enter the list items : 1 2 2 5 8 4 4 8 5 9 9
No of unique items in the list are: 6
